dashboard/config/routes.rb
    get '/users/migrate_to_multi_auth', to: 'registrations#migrate_to_multi_auth'
    get '/users/demigrate_from_multi_auth', to: 'registrations#demigrate_from_multi_auth'
    get '/users/to_destroy', to: 'registrations#users_to_destroy'
    get '/reset_session', to: 'sessions#reset'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  get 'discourse/sso' => 'discourse_sso#sso'
  post '/auth/lti', to: 'lti_provider#sso'

  root to: "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  namespace :home do
    HomeController.instance_methods(false).each do |action|
      get action, action: action
    end
  end

  resources :p, path: '/p/', only: [:index] do
    collection do
      ProjectsController::STANDALONE_PROJECTS.each do |key, value|
        get '/' + key.to_s, to: 'projects#redirect_legacy', key: value[:name], as: key.to_s
      end
      get '/', to: redirect('/projects')
    end
  end

  get 'projects/featured', to: 'projects#featured'
  put '/featured_projects/:project_id/unfeature', to: 'featured_projects#unfeature'
  put '/featured_projects/:project_id/feature', to: 'featured_projects#feature'

  get '/projects/public', to: 'projects#public'
  resources :projects, path: '/projects/', only: [:index] do
    collection do
      ProjectsController::STANDALONE_PROJECTS.each do |key, _|
        get "/#{key}", to: 'projects#load', key: key.to_s, as: "#{key}_project"
        get "/#{key}/new", to: 'projects#create_new', key: key.to_s, as: "#{key}_project_create_new"
        get "/#{key}/:channel_id", to: 'projects#show', key: key.to_s, as: "#{key}_project_share", share: true
        get "/#{key}/:channel_id/edit", to: 'projects#edit', key: key.to_s, as: "#{key}_project_edit"
        get "/#{key}/:channel_id/view", to: 'projects#show', key: key.to_s, as: "#{key}_project_view", readonly: true
        get "/#{key}/:channel_id/embed", to: 'projects#show', key: key.to_s, as: "#{key}_project_iframe_embed", iframe_embed: true
        get "/#{key}/:channel_id/remix", to: 'projects#remix', key: key.to_s, as: "#{key}_project_remix"
        get "/#{key}/:channel_id/export_create_channel", to: 'projects#export_create_channel', key: key.to_s, as: "#{key}_project_export_create_channel"
        get "/#{key}/:channel_id/export_config", to: 'projects#export_config', key: key.to_s, as: "#{key}_project_export_config"
      end
    end
  end

  post '/locale', to: 'home#set_locale', as: 'locale'

  # quick links for cartoon network arabic
  get '/flappy/lang/ar', to: 'home#set_locale', as: 'flappy/lang/ar', locale: 'ar-SA', user_return_to: '/flappy/1'
  get '/playlab/lang/ar', to: 'home#set_locale', as: 'playlab/lang/ar', locale: 'ar-SA', user_return_to: '/s/playlab/stage/1/puzzle/1'
  get '/artist/lang/ar', to: 'home#set_locale', as: 'artist/lang/ar', locale: 'ar-SA', user_return_to: '/s/artist/stage/1/puzzle/1'

  # /lang/xx shortcut for all routes
  get '/lang/:locale', to: 'home#set_locale', user_return_to: '/'
  get '*i18npath/lang/:locale', to: 'home#set_locale'

  get 'pools', to: 'pools#index', as: 'pools'
  scope 'pools/:pool' do
    resources :blocks, constraints: {id: /[^\/]+/}
  end
  resources :shared_blockly_functions, path: '/functions'
  resources :libraries

  resources :levels do
    member do
      get 'get_rubric'
      get 'embed_level'
      get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
      post 'update_properties'
      post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
      post 'clone'
    end
  end

  post 'level_assets/upload', to: 'level_assets#upload'

  resources :level_starter_assets, only: [:show], param: 'level_name', constraints: {level_name: /[^\/]+/} do
    member do
      get '/:filename', to: 'level_starter_assets#file'
      post '', to: 'level_starter_assets#upload'
      delete '/:filename', to: 'level_starter_assets#destroy'
    end
  end

  resources :scripts, path: '/s/' do
    # /s/xxx/reset
    get 'reset', to: 'script_levels#reset'
    get 'next', to: 'script_levels#next'
    get 'hidden_stages', to: 'script_levels#hidden_stage_ids'
    post 'toggle_hidden', to: 'script_levels#toggle_hidden'

    get 'instructions', to: 'scripts#instructions'

    # /s/xxx/stage/yyy/puzzle/zzz
    resources :stages, only: [], path: "/stage", param: 'position', format: false do
      get 'extras', to: 'script_levels#stage_extras', format: false
      get 'summary_for_lesson_plans', to: 'script_levels#summary_for_lesson_plans', format: false
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
        member do
          # /s/xxx/stage/yyy/puzzle/zzz/page/ppp
          get 'page/:puzzle_page', to: 'script_levels#show', as: 'puzzle_page', format: false
          # /s/xxx/stage/yyy/puzzle/zzz/sublevel/sss
          get 'sublevel/:sublevel_position', to: 'script_levels#show', as: 'sublevel', format: false
        end
      end
    end

    # /s/xxx/lockable/yyy/puzzle/zzz
    resources :lockable_stages, only: [], path: "/lockable", param: 'position', format: false do
      get 'summary_for_lesson_plans', to: 'script_levels#summary_for_lesson_plans', format: false
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
        member do
          # /s/xxx/stage/yyy/puzzle/zzz/page/ppp
          get 'page/:puzzle_page', to: 'script_levels#show', as: 'puzzle_page', format: false
        end
      end
    end

    get 'preview-assignments', to: 'plc/enrollment_evaluations#preview_assignments', as: 'preview_assignments'
    post 'confirm_assignments', to: 'plc/enrollment_evaluations#confirm_assignments', as: 'confirm_assignments'

    get 'pull-review', to: 'peer_reviews#pull_review', as: 'pull_review'
  end

  resources :courses, param: 'course_name'
  get '/course/:course_name', to: redirect('/courses/%{course_name}')

  get '/beta', to: redirect('/')

  get '/hoc/reset', to: 'script_levels#reset', script_id: Script::HOC_NAME, as: 'hoc_reset'
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_NAME, as: 'hoc_chapter', format: false

  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_NAME, as: 'flappy_chapter', format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_NAME, as: 'jigsaw_chapter', format: false

  get '/weblab/host', to: 'weblab_host#index'

  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join(/:section_code)', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/level/:level_id', to: 'activities#milestone', as: 'milestone_level'
  post '/milestone/:user_id/:script_level_id', to: 'activities#milestone', as: 'milestone'
  post '/milestone/:user_id/:script_level_id/:level_id', to: 'activities#milestone', as: 'milestone_script_level'

  get '/admin', to: 'admin_reports#directory', as: 'admin_directory'
  resources :regional_partners
  post 'regional_partners/:id/assign_program_manager', controller: 'regional_partners', action: 'assign_program_manager'
  get 'regional_partners/:id/remove_program_manager/:program_manager_id', controller: 'regional_partners', action: 'remove_program_manager'
  post 'regional_partners/:id/add_mapping', controller: 'regional_partners', action: 'add_mapping'
  get 'regional_partners/:id/remove_mapping/:id', controller: 'regional_partners', action: 'remove_mapping'

  # HOC dashboards.
  get '/admin/hoc/students_served', to: 'admin_hoc#students_served', as: 'hoc_students_served'

  # internal report dashboards
  get '/admin/levels', to: 'admin_reports#level_completions', as: 'level_completions'
  get '/admin/level_answers(.:format)', to: 'admin_reports#level_answers', as: 'level_answers'
  get '/admin/pd_progress(/:script)', to: 'admin_reports#pd_progress', as: 'pd_progress'
  get '/admin/debug', to: 'admin_reports#debug'

  # internal search tools
  get '/admin/find_students', to: 'admin_search#find_students', as: 'find_students'
  get '/admin/lookup_section', to: 'admin_search#lookup_section', as: 'lookup_section'
  post '/admin/lookup_section', to: 'admin_search#lookup_section'
  post '/admin/undelete_section', to: 'admin_search#undelete_section', as: 'undelete_section'
  get '/admin/pilots/:pilot_name', to: 'admin_search#show_pilot', as: 'show_pilot'

  # internal engineering dashboards
  get '/admin/dynamic_config', to: 'dynamic_config#show', as: 'dynamic_config_state'
  get '/admin/feature_mode', to: 'feature_mode#show', as: 'feature_mode'
  post '/admin/feature_mode', to: 'feature_mode#update', as: 'feature_mode_update'

  # internal support tools
  get '/admin/account_repair', to: 'admin_users#account_repair_form', as: 'account_repair_form'
  post '/admin/account_repair', to: 'admin_users#account_repair',  as: 'account_repair'
  get '/admin/assume_identity', to: 'admin_users#assume_identity_form', as: 'assume_identity_form'
  post '/admin/assume_identity', to: 'admin_users#assume_identity', as: 'assume_identity'
  post '/admin/undelete_user', to: 'admin_users#undelete_user', as: 'undelete_user'
  get '/admin/manual_pass', to: 'admin_users#manual_pass_form', as: 'manual_pass_form'
  post '/admin/manual_pass', to: 'admin_users#manual_pass', as: 'manual_pass'
  get '/admin/permissions', to: 'admin_users#permissions_form', as: 'permissions_form'
  post '/admin/grant_permission', to: 'admin_users#grant_permission', as: 'grant_permission'
  get '/admin/revoke_permission', to: 'admin_users#revoke_permission', as: 'revoke_permission'
  post '/admin/bulk_grant_permission', to: 'admin_users#bulk_grant_permission', as: 'bulk_grant_permission'
  get '/admin/studio_person', to: 'admin_users#studio_person_form', as: 'studio_person_form'

dashboard/app/views/shared/_check_admin.html.haml
- if @script && Gatekeeper.allows('requires_hoc_secret', where: {script_name: @script.name})
  %script{src: minifiable_asset_path('js/shared/_check_admin.js'),
          data: {checkadmin: Digest::MD5.hexdigest(DCDO.get("hoc_secret", '')).to_json}}

dashboard/app/views/shared/_course_progress_block.html.haml
.course_progress{style: 'float: left; position: relative;'}
  .courseblock-span3.courseblock-wide-small{style: 'width: 460px; height: 150px;'}
    =link_to script_url(script.id) do
      %h3= data_t_suffix('script.name', script.name, 'title')
      .clear
      .smalltext= data_t_suffix('script.name', script.name, 'description_short')
      .clear
    - if current_user.completed?(script)
      =link_to script_url(script.id) do
        .audiencebar.bottombartext.printcertificatelight= t('home.view_course')
      %a{href: script_certificate_image_url(current_user, script)}
        .bottombar.bottombartext.printcertificate{style: 'bottom: 0; position: absolute'}= t('home.print_certificate')
    - elsif current_user.not_started?(script)
      =link_to script_url(script.id) do
        .audiencebar.bottombartext.trynowlight= t('home.view_course')
      %a{href: script_url(script.id)}
        .bottombar.bottombartext.trynow{style: 'bottom: 0; position: absolute'}= t('home.trynow')
    - else
      =link_to script_url(script.id) do
        .audiencebar.bottombartext.continuelight= t('home.view_course')
      %a{href: build_script_level_url(current_user.next_unpassed_progression_level(script))}
        .bottombar.bottombartext.continue{style: 'bottom: 0; position: absolute'}= t('continue')

dashboard/app/views/shared/_course_tall_block.haml
- show_teacher_guide ||= false
- block_data ||= CourseBlockHelper.get_tall_course_block(id)

- if block_data
  .courseblock-span3.courseblock-tall
    = link_to block_data[:url] do
      = image_tag block_data[:image_url], height: '120px', width: '100%'
      .course-container
        - if Script.beta? id
          .beta
            %h3.betatitle= block_data[:title]
            %h3.betatext= t('beta')
        - else
          %h3.heading= block_data[:title]
        - if block_data[:audience]
          .text= block_data[:audience]
        .text.smalltext= block_data[:body]
        - if show_teacher_guide && block_data[:teacher_guide]&.present?
          .teacher-guide= link_to t('view_teacher_guide'), block_data[:teacher_guide]

dashboard/app/views/shared/_course_wide_block.haml
- if id == Script::HOC_NAME
  .courseblock-span6.courseblock-wide-small
    = link_to hoc_reset_url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/codehoc3.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.hoc.title')
        .smalltext= t('upsell.hoc.body')

- elsif id == Script::FLAPPY_NAME
  .courseblock-span6.courseblock-wide-small
    = link_to script_reset_url(Script::FLAPPY_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.studio_url('/blockly/media/skins/flappy/small_static_avatar.png')}
      .courseblock-span4.heading
        %h3= t('upsell.flappy.title')
        .smalltext= t('upsell.flappy.body')

- elsif ['applab', 'gamelab', 'widgets', 'weblab'].include? id
  - url = CDO.code_org_url(id)
  .courseblock-span6.courseblock-wide-small{style: "min-height: 215px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url("/shared/images/courses/fit-130x180/logo_#{id}_tall.jpg")}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        %h4= t("upsell.#{id}.audience")
        .smalltext= t("upsell.#{id}.body")
      .bottombar.smalltext.trynow= t("upsell.#{id}.cta")

- elsif id == Script::TWENTY_HOUR_NAME && view == 'large'
  - url = script_reset_url(id)
  .courseblock-span6.courseblock-wide-large
    = link_to script_url(Script::TWENTY_HOUR_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/code20hr.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.20-hour.title')
        %h4= data_t_suffix('script.name', '20-hour', 'description_audience')
        .smalltext= t('upsell.20-hour.body')

- elsif id == Script::TWENTY_HOUR_NAME && view == 'small'
  - url = script_reset_url(id)
  - audience = data_t_suffix('script.name', id, 'description_audience')
  .courseblock-span6.courseblock-wide-small{style: "min-height: 120px;"}
    = link_to script_url(Script::TWENTY_HOUR_NAME) do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/code20hr.jpg')}
      .courseblock-span4.heading
        %h3= t('upsell.20-hour.title')
        .smalltext= t('upsell.20-hour.body_short')

- elsif id == 'unplugged' && view == 'large'
  - url = CDO.code_org_url("/curriculum/unplugged")
  .courseblock-span6.courseblock-wide-large
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/unplugged.png')}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        %h4= t("upsell.#{id}.audience")
        .smalltext= t("upsell.#{id}.body")

- elsif id == 'unplugged' && view == 'small'
  - url = CDO.code_org_url("/curriculum/unplugged")
  .courseblock-span6.courseblock-wide-small{style: "min-height: 120px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url('/images/fit-150x100/unplugged.png')}
      .courseblock-span4.heading
        %h3= t("upsell.#{id}.title")
        .smalltext= t("upsell.#{id}.body_short")

- elsif [Script::ARTIST_NAME, Script::PLAYLAB_NAME].include? id
  - url = script_reset_url(id)
  - title = data_t_suffix('script.name', id, 'title')
  - body = data_t_suffix('script.name', id, 'description_short')
  .courseblock-span6.courseblock-wide-small{style: "min-height: 100px;"}
    = link_to url do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url("/shared/images/courses/fill-150x110/logo_tall_#{id}.jpg")}
      .courseblock-span4.heading
        %h3= title
        .smalltext= body

- elsif [Script::EXPRESS_NAME, Script::PRE_READER_EXPRESS_NAME].include? id
  .courseblock-span6.courseblock-wide-small{style: "min-height: 140px;"}
    = link_to script_url(id)  do
      .courseblock-span2.imgspan
        %img{src: CDO.code_org_url("/shared/images/courses/fill-150x110/logo_tall_#{id}.jpg")}
      .courseblock-span4.heading
        %h3= data_t_suffix('script.name', id, 'title')
        .smalltext= data_t_suffix('script.name', id, 'description_short')

- elsif [Script::COURSE1_NAME, Script::COURSE2_NAME, Script::COURSE3_NAME, Script::COURSE4_NAME, Script::ALGEBRA_NAME].include? id
  .courseblock-span6.courseblock-wide-large
    =link_to script_url(id) do
      .courseblock-span2.imgspan
        = image_tag(CDO.shared_image_url("courses/fit-150x100/logo_#{id}.jpg"))
      .courseblock-span4.heading
        %h3
          = data_t_suffix('script.name', id, 'title')
          - if Script.beta? id
            &nbsp;
            %span.betatext
              = t('beta')
        %h4= data_t_suffix('script.name', id, 'description_audience')
        .smalltext= data_t_suffix('script.name', id, 'description')

dashboard/app/views/shared/_extra_links.html.haml
.extra-links
  %h4
    Extra Links:
    %a{href: '#', onclick: 'return extraLinksClick()'} [hide/show]
  .content
    = yield

:javascript

  var extraLinksBox;

  $().ready(function() {
    extraLinksBox = $(".extra-links .content");
    if (document.cookie.indexOf('hide-extra-links-menu') >= 0) {
      extraLinksBox.hide();
    }
  });

  // Toggles the visibility of the links, setting a cookie to preserve the
  // preference.
  function extraLinksClick() {
    extraLinksBox.toggle();
    if (extraLinksBox.is(":visible")) {
      // Clear the cookie using a blank value and a date in the past.
      document.cookie = "hide-extra-links-menu=; expires=Thu, 01 Jan 1970 00:00:00 UTC;";
    } else {
      // Set the cookie and make it expire far into the future.
      document.cookie="hide-extra-links-menu=true; expires=Fri, 31 Dec 9999 23:59:59 GMT;";
    }
    return false;
  }

dashboard/app/views/shared/_header_progress.html.haml
- small_text = @script && (@script.name == "starwars" || @script.name == "starwarsblocks")
- if @stage_extras
  - text = @stage.localized_title
- else
  - stage = @stage || @script_level.stage
  - text = @script.professional_learning_course? ? stage.localized_name : stage.localized_title

-# Pass along section_id param so that when teacher moves between lesson page and course overview
-# they maintain their section.
-section_id = request.query_parameters[:section_id]
-user_id = request.query_parameters[:user_id]

.header_level
  .header_level_container
    .script_name_container
    .progress_container
    .header_finished_link{style: 'display: none;', class: ('small_font_on_tablet' if small_text)}
    %span.header_popup_link{style: 'display: none;'}
      .header_popup_link_glyph
        &#x25BC;
      .header_popup_link_text= t(:more)
.header_popup
  .header_popup_scrollable
    .header_popup_body
      .user-stats-block

- content_for(:body_scripts) do
  - script_data = {scriptName: {name: text,
    href: script_path(@script, section_id: section_id, user_id: user_id),
    smallText: small_text}.to_json}
  %script{type: "text/javascript", src: minifiable_asset_path('js/shared/_header_progress.js'), data: script_data}

dashboard/app/views/shared/_maybe_set_hoc_secret.html.haml
- if current_user && current_user.permission?(UserPermission::LEVELBUILDER)
  -# For levelbuilders, set a client-side secret that allows them to access restricted HOC levels.
  :javascript
    //<![CDATA[
    try {
      localStorage.setItem('hoc_secret', '#{DCDO.get("hoc_secret", nil)}');
    } catch(e) {}
    //]]>
- elsif params[:hoc_secret]
  -# Allow non-admins to specify the secret via a query string parameter.
  :javascript
    //<![CDATA[
    try {
      localStorage.setItem('hoc_secret', '#{escape_javascript(params[:hoc_secret])}')
    } catch(e) {}
    //]]>

dashboard/app/views/shared/_school_info.html.haml
- require 'country_codes'
- require 'state_abbr'
- require 'geocoder'

- location = Geocoder.search(request.ip).try(:first)
-# geocoder sometimes shows localhost's country as RD/Reserved
- us_ip = location.nil? || ['US', 'RD'].include?(location.country_code.to_s.upcase)
- existing_school_info ||= {}
- existing_school_info[:country] ||= 'US' if us_ip

- content_for(:head) do
  %script{src: minifiable_asset_path('js/shared/_school_info.js')}

#pl-application-form
  #pl-application-facets.form-section
    .form-group#school-country-group
      .question School Country
      %select#school-country.form-control{name: "#{form_name}[country]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        - COUNTRY_CODE_TO_COUNTRY_NAME.keys.each do |code|
          %option{value: code}= country_name_from_code(code)

    .form-group
      .question Select school type
      %select#school-type.form-control{name: "#{form_name}[school_type]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        %option{value: SchoolInfo::SCHOOL_TYPE_CHARTER} Charter
        %option{value: SchoolInfo::SCHOOL_TYPE_PRIVATE} Private
        %option{value: SchoolInfo::SCHOOL_TYPE_PUBLIC} Public
        %option{value: SchoolInfo::SCHOOL_TYPE_OTHER} Other

    .form-group{style: "display: none;"}
      .question State
      %select#school-state.form-control{name: "#{form_name}[school_state]", type: "select", required: false}
        %option{value: "", selected: true, disabled: true}
        - get_all_states_with_dc.each do |state_abbr, state_name|
          %option{value: state_abbr}= state_name

    .form-group{style: "display: none;"}
      .question District
      #school-district

        -# We'll apply the Selectize UI control to this input.
        %input#school-district-id.form-control{name: "#{form_name}[school_district_id]", type: "text", required: false}

        %label
          %input#school-district-other{name: "#{form_name}[school_district_other]", type: "checkbox", value: "true", style: "margin-top: 0px"}
          %span{style: "font-size: 12px"}
            Other district not listed above

        .form-group{style: "display: none;"}
          .question District Name
          %div.controls
            %input#school-district-name.form-control{name: "school_info[school_district_name]", type: "text", required: false, style: "width: calc(100% - 15px);"}

    .form-group{style: "display: none;"}
      .question School
      #school

        -# We'll apply the Selectize UI control to this input.
        %input#school-id.form-control{name: "#{form_name}[school_id]", type: "text", required: false}

        %label
          %input#school-other{name: "#{form_name}[school_other]", type: "checkbox", value: "true", style: "margin-top: 0px"}
          %span{style: "font-size: 12px"}
            Other school not listed above

    #no-schools-warning{style: "display: none; margin-bottom: 5px;"}
      .question No schools of that type were found in this district.

    -# '#school-name' is outside of '#school' so that we can still show it when the school dropdown is hidden.
    .form-group{style: "display: none;"}
      .question
        School Name
      %div.controls
        %input#school-name.form-control{name: "school_info[school_name]", type: "text", required: false, style: "width: calc(100% - 15px);"}

    .form-group{style: "display: none;"}
      .question School’s ZIP code
      %input#school-zipcode.form-control{name: "#{form_name}[school_zip]", type: "text", required: false}

    .form-group{style: "display: none;"}
      .question
        School Address
      %div.controls
        %textarea#school-address.form-control{name: "school_info[full_address]", required: false, rows: 4, maxlength: 255, style: "width: calc(100% - 15px);"}

:javascript

  $(document).ready(function() {
    var options = #{existing_school_info.to_json};
    var suppressScrolling = #{!!(local_assigns[:suppress_scrolling])};
    options['suppressScrolling'] = suppressScrolling;
    options['assumeUsa'] = #{!!(local_assigns[:assume_usa])};

    // Send through some values that the JavaScript will need.
    window.schoolInfoManager = new SchoolInfoManager(options);
  });

dashboard/app/views/shared/_sharing_meta_tags.html.haml
-# only works for pages that have a @level
- if @level && @level.game.supports_sharing?
  - content_for :og do
    = tag 'meta', name: 'viewport', content: 'initial-scale=1'

    -# facebook boilerplate
    = tag 'meta', property: 'fb:app_id', content: '500177453358606'
    = tag 'meta', property: 'og:site_name', content: 'Code.org'
    = tag 'meta', property: 'og:type', content: 'article'
    = tag 'meta', property: 'article:publisher', content: 'https://www.facebook.com/Code.org'

    -# twitter boilerplate
    = tag 'meta', name: 'twitter:site', content: '@codeorg'

    - if @level.game.app == Game::DANCE
      = tag 'meta', name: 'twitter:card', content: 'summary'
    - else
      = tag 'meta', name: 'twitter:card', content: 'photo'

    - if @level.game.app == Game::ARTIST
      - meta_image_width = 500
      - meta_image_height = 261
    - else
      - meta_image_width = 400
      - meta_image_height = 400

    -# several meta tags are the same for facebook/og and twitter
    - {og: 'property', twitter: 'name'}.each do |namespace, attr|
      = tag 'meta', attr => "#{namespace}:title", content: t('share_code.check_out_what_i_made')
      = tag 'meta', attr => "#{namespace}:description", content: t('share_code.og_description')
      = tag 'meta', attr => "#{namespace}:url", content: request.original_url

      - if @project_image
        = tag 'meta', attr => "#{namespace}:image", content: @project_image
        = tag 'meta', attr => "#{namespace}:image:secure_url", content: @project_image
      - else
        = tag 'meta', attr => "#{namespace}:image", content: meta_image_url(level_source: @level_source, level: @level)
        = tag 'meta', attr => "#{namespace}:image:secure_url", content: meta_image_url(level_source: @level_source, level: @level)
      = tag 'meta', attr => "#{namespace}:image:width", content: meta_image_width
      = tag 'meta', attr => "#{namespace}:image:height", content: meta_image_height

    = tag :meta, name: 'mobile-web-app-capable', content: 'yes'
    = tag :meta, name: 'apple-mobile-web-app-capable', content: 'yes'
    = tag :meta, name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent'
    - if @level_source.try(:level_source_image).try(:image)
      = tag :link, rel: 'apple-touch-icon', href: meta_image_url(level_source: @level_source, level: @level)
    - elsif @level.game.flappy?
      = tag :link, rel: 'apple-touch-icon', href: asset_url('flappy_icon.png')
    - else
      = tag :link, rel: 'apple-touch-icon', href: asset_url('logo_noalpha.png')