dashboard/config/routes.rb
# For documentation see, e.g., http://guides.rubyonrails.org/routing.html.

Dashboard::Application.routes.draw do
  # React-router will handle sub-routes on the client.
  get 'teacher_dashboard/sections/:section_id/*path', to: 'teacher_dashboard#show', via: :all
  get 'teacher_dashboard/sections/:section_id', to: 'teacher_dashboard#show'

  resources :survey_results, only: [:create], defaults: {format: 'json'}

  resource :pairing, only: [:show, :update]

  resources :user_levels, only: [:update, :destroy]

  patch '/api/v1/user_scripts/:script_id', to: 'api/v1/user_scripts#update'

  get '/download/:product', to: 'hoc_download#index'

  get '/terms-and-privacy', to: 'home#terms_and_privacy'
  get '/dashboardapi/terms-and-privacy', to: "home#terms_and_privacy"
  get '/dashboardapi/hoc-courses-teacher-guides', to: "home#hoc_courses_teacher_guides"
  get '/dashboardapi/hoc-courses-challenge', to: "home#hoc_courses_challenge"

  get "/home", to: "home#home"

  get "/congrats", to: "congrats#index"

  resources :gallery_activities, path: '/gallery' do
    collection do
      get 'art', to: 'gallery_activities#index', app: Game::ARTIST
      get 'apps', to: 'gallery_activities#index', app: Game::PLAYLAB
    end
  end
  resources :activity_hints, only: [:update]

  resources :hint_view_requests, only: [:create]
  resources :authored_hint_view_requests, only: [:create]

  resources :puzzle_ratings, only: [:create]
  resources :callouts
  resources :videos do
    collection do
      get 'test'
      get 'embed/:key', to: 'videos#embed', as: 'embed'
    end
  end

  get 'maker/home', to: 'maker#home'
  get 'maker/setup', to: 'maker#setup'
  get 'maker/discountcode', to: 'maker#discountcode'
  post 'maker/apply', to: 'maker#apply'
  post 'maker/schoolchoice', to: 'maker#schoolchoice'
  post 'maker/complete', to: 'maker#complete'
  get 'maker/application_status', to: 'maker#application_status'
  post 'maker/override', to: 'maker#override'

  # Media proxying
  get 'media', to: 'media_proxy#get', format: false

  # XHR proxying
  get 'xhr', to: 'xhr_proxy#get', format: false

  get 'redirected_url', to: 'redirect_proxy#get', format: false

  get 'docs/*path', to: 'curriculum_proxy#get_doc'
  get 'curriculum/*path', to: 'curriculum_proxy#get_curriculum'

  # Override Error Codes
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_server_error"

  # User-facing section routes
  resources :sections, only: [:show] do
    member do
      post 'log_in'
    end
  end
  # Section API routes (JSON only)
  concern :section_api_routes do
    resources :sections, only: [:index, :show, :create, :update, :destroy] do
      resources :students, only: [:index, :update], controller: 'sections_students' do
        collection do
          post 'bulk_add'
          get 'completed_levels_count'
        end
        member do
          post 'remove'
        end
      end
      member do
        post 'join'
        post 'leave'
        post 'update_sharing_disabled'
        get 'student_script_ids'
      end
      collection do
        get 'membership'
        get 'valid_scripts'
      end
    end
  end

  # Used in react assessments tab
  concern :assessments_routes do
    resources :assessments, only: [:index] do
      collection do
        get 'section_responses'
        get 'section_surveys'
        get 'section_feedback'
      end
    end
  end

  post '/dashboardapi/sections/transfers', to: 'transfers#create'
  post '/api/sections/transfers', to: 'transfers#create'

  get '/sh/:id', to: redirect('/c/%{id}')
  get '/sh/:id/:action_id', to: redirect('/c/%{id}/%{action_id}')

  get '/u/:id', to: redirect('/c/%{id}')
  get '/u/:id/:action_id', to: redirect('/c/%{id}/%{action_id}')

  # These links should no longer be created (August 2017), though we will continue to support
  # existing links. Instead, create /r/ links.
  resources :level_sources, path: '/c/', only: [:show, :edit, :update] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end
  # These routes are being created to replace the /c/ routes (August 2017) so as to include the ID
  # of the sharing user in the URL. Doing so allows us to block showing the level source if the user
  # deletes themself.
  resources :obfuscated_level_sources, path: '/r/', controller: :level_sources, param: :level_source_id_and_user_id, only: [:show, :edit, :update] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end

  get '/share/:id', to: redirect('/c/%{id}')

  devise_scope :user do
    get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
    post '/users/begin_sign_up', to: 'registrations#begin_sign_up'
    patch '/dashboardapi/users', to: 'registrations#update'
    patch '/users/upgrade', to: 'registrations#upgrade'
    patch '/users/set_age', to: 'registrations#set_age'
    patch '/users/email', to: 'registrations#set_email'
    patch '/users/user_type', to: 'registrations#set_user_type'
    get '/users/cancel', to: 'registrations#cancel'
    get '/users/clever_takeover', to: 'sessions#clever_takeover'
    get '/users/clever_modal_dismissed', to: 'sessions#clever_modal_dismissed'
    get '/users/auth/:provider/connect', to: 'authentication_options#connect'
    delete '/users/auth/:id/disconnect', to: 'authentication_options#disconnect'
    get '/users/migrate_to_multi_auth', to: 'registrations#migrate_to_multi_auth'
    get '/users/demigrate_from_multi_auth', to: 'registrations#demigrate_from_multi_auth'
    get '/users/to_destroy', to: 'registrations#users_to_destroy'
    get '/reset_session', to: 'sessions#reset'
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  get 'discourse/sso' => 'discourse_sso#sso'
  post '/auth/lti', to: 'lti_provider#sso'

  root to: "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  namespace :home do
    HomeController.instance_methods(false).each do |action|
      get action, action: action
    end
  end

  resources :p, path: '/p/', only: [:index] do
    collection do
      ProjectsController::STANDALONE_PROJECTS.each do |key, value|
        get '/' + key.to_s, to: 'projects#redirect_legacy', key: value[:name], as: key.to_s
      end
      get '/', to: redirect('/projects')
    end
  end

  get 'projects/featured', to: 'projects#featured'
  put '/featured_projects/:project_id/unfeature', to: 'featured_projects#unfeature'
  put '/featured_projects/:project_id/feature', to: 'featured_projects#feature'

  get '/projects/public', to: 'projects#public'
  resources :projects, path: '/projects/', only: [:index] do
    collection do
      ProjectsController::STANDALONE_PROJECTS.each do |key, _|
        get "/#{key}", to: 'projects#load', key: key.to_s, as: "#{key}_project"
        get "/#{key}/new", to: 'projects#create_new', key: key.to_s, as: "#{key}_project_create_new"
        get "/#{key}/:channel_id", to: 'projects#show', key: key.to_s, as: "#{key}_project_share", share: true
        get "/#{key}/:channel_id/edit", to: 'projects#edit', key: key.to_s, as: "#{key}_project_edit"
        get "/#{key}/:channel_id/view", to: 'projects#show', key: key.to_s, as: "#{key}_project_view", readonly: true
        get "/#{key}/:channel_id/embed", to: 'projects#show', key: key.to_s, as: "#{key}_project_iframe_embed", iframe_embed: true
        get "/#{key}/:channel_id/remix", to: 'projects#remix', key: key.to_s, as: "#{key}_project_remix"
        get "/#{key}/:channel_id/export_create_channel", to: 'projects#export_create_channel', key: key.to_s, as: "#{key}_project_export_create_channel"
        get "/#{key}/:channel_id/export_config", to: 'projects#export_config', key: key.to_s, as: "#{key}_project_export_config"
      end
    end
  end

  post '/locale', to: 'home#set_locale', as: 'locale'

  # quick links for cartoon network arabic
  get '/flappy/lang/ar', to: 'home#set_locale', as: 'flappy/lang/ar', locale: 'ar-SA', user_return_to: '/flappy/1'
  get '/playlab/lang/ar', to: 'home#set_locale', as: 'playlab/lang/ar', locale: 'ar-SA', user_return_to: '/s/playlab/stage/1/puzzle/1'
  get '/artist/lang/ar', to: 'home#set_locale', as: 'artist/lang/ar', locale: 'ar-SA', user_return_to: '/s/artist/stage/1/puzzle/1'

  # /lang/xx shortcut for all routes
  get '/lang/:locale', to: 'home#set_locale', user_return_to: '/'
  get '*i18npath/lang/:locale', to: 'home#set_locale'

  get 'pools', to: 'pools#index', as: 'pools'
  scope 'pools/:pool' do
    resources :blocks, constraints: {id: /[^\/]+/}
  end
  resources :shared_blockly_functions, path: '/functions'
  resources :libraries

  resources :levels do
    member do
      get 'get_rubric'
      get 'embed_level'
      get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
      post 'update_properties'
      post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
      post 'clone'
    end
  end

  post 'level_assets/upload', to: 'level_assets#upload'

  resources :level_starter_assets, only: [:show], param: 'level_name', constraints: {level_name: /[^\/]+/} do
    member do
      get '/:filename', to: 'level_starter_assets#file'
      post '', to: 'level_starter_assets#upload'
      delete '/:filename', to: 'level_starter_assets#destroy'
    end
  end

  resources :scripts, path: '/s/' do
    # /s/xxx/reset
    get 'reset', to: 'script_levels#reset'
    get 'next', to: 'script_levels#next'
    get 'hidden_stages', to: 'script_levels#hidden_stage_ids'
    post 'toggle_hidden', to: 'script_levels#toggle_hidden'

    get 'instructions', to: 'scripts#instructions'

    # /s/xxx/stage/yyy/puzzle/zzz
    resources :stages, only: [], path: "/stage", param: 'position', format: false do

dashboard/app/controllers/home_controller.rb
require 'census_helper'

class HomeController < ApplicationController
  include UsersHelper
  before_action :authenticate_user!, only: :gallery_activities

  # Don't require an authenticity token on set_locale because we post to that
  # action from publicly cached page without a valid token. The worst case impact
  # is that an attacker could change a user's language if they fooled them into
  # clicking on a link.
  skip_before_action :verify_authenticity_token, only: 'set_locale'

  # The terms_and_privacy page gets loaded in an iframe on the signup page, so skip
  # clearing the sign up tracking variables
  skip_before_action :clear_sign_up_session_vars, only: [:terms_and_privacy]

  def set_locale
    set_locale_cookie(params[:locale]) if params[:locale]
    if params[:i18npath]
      redirect_to "/#{params[:i18npath]}"
    elsif params[:user_return_to]
      redirect_to URI.parse(params[:user_return_to].to_s).path
    else
      redirect_to '/'
    end
  rescue URI::InvalidURIError
    redirect_to '/'
  end

  def home_insert
    if current_user
      render 'index', layout: false, formats: [:html]
    else
      render text: ''
    end
  end

  def health_check
    render text: 'healthy!'
  end

  GALLERY_PER_PAGE = 5

  # Signed in student, with an assigned course/script: redirect to course overview page
  # Note: the student will be redirected to the course or script in which they
  # most recently made progress, which may not be an assigned course or script.
  # Signed in student or teacher, without an assigned course/script: redirect to /home
  # Signed out: redirect to /courses
  def index
    if current_user
      if should_redirect_to_script_overview?
        redirect_to script_path(current_user.most_recently_assigned_script)
      else
        redirect_to '/home'
      end
    else
      clear_takeover_session_variables
      redirect_to '/courses'
    end
  end

  # Signed in: render home page
  # Signed out: redirect to sign in
  def home
    authenticate_user!
    init_homepage
    render 'home/index'
  end

  def gallery_activities
    if current_user
      @gallery_activities =
        current_user.gallery_activities.order(id: :desc).page(params[:page]).per(GALLERY_PER_PAGE)
    end
    render partial: 'home/gallery_content'
  end

  def certificate_link_test
    render 'certificate_link_test', formats: [:html]
  end

  # This static page combines TOS and Privacy partials all in one page
  # for easy printing.
  def terms_and_privacy
    render partial: 'home/tos_and_privacy'
  end

  private

  def should_redirect_to_script_overview?
    current_user.student? &&
    !account_takeover_in_progress? &&
    current_user.can_access_most_recently_assigned_script? &&
    (
      !current_user.user_script_with_most_recent_progress ||
      current_user.most_recent_progress_in_recently_assigned_script? ||
      current_user.last_assignment_after_most_recent_progress?
    )
  end

  # Set all local variables needed to render the signed-in homepage.
  # @raise if called when the user is not signed in.
  def init_homepage
    raise 'init_homepage can only be called when there is a current_user' unless current_user

    @homepage_data = {}
    @homepage_data[:valid_grades] = Section.valid_grades
    @homepage_data[:stageExtrasScriptIds] = Script.stage_extras_script_ids
    @homepage_data[:isEnglish] = request.language == 'en'
    @homepage_data[:locale] = Script.locale_english_name_map[request.locale]
    @homepage_data[:canViewAdvancedTools] = !(current_user.under_13? && current_user.terms_version.nil?)
    @homepage_data[:providers] = current_user.providers

    @force_race_interstitial = params[:forceRaceInterstitial]
    @force_school_info_confirmation_dialog = params[:forceSchoolInfoConfirmationDialog]
    @force_school_info_interstitial = params[:forceSchoolInfoInterstitial]

    student_sections = current_user.sections_as_student.map(&:summarize_without_students)

    # Students and teachers will receive a @top_course for their primary
    # script, so we don't want to include that script (if it exists) in the
    # regular lists of recent scripts.
    exclude_primary_script = true
    @homepage_data[:courses] = current_user.recent_courses_and_scripts(exclude_primary_script)

    @homepage_data[:hasFeedback] = current_user.student? && TeacherFeedback.where(
      student_id: current_user.id
    ).count > 0

    script = current_user.primary_script
    if script
      script_level = current_user.next_unpassed_progression_level(script)
    end
    @homepage_data[:topCourse] = nil
    if script && script_level
      @homepage_data[:topCourse] = {
        assignableName: data_t_suffix('script.name', script[:name], 'title'),
        lessonName: script_level.stage.localized_title,
        linkToOverview: script_path(script),
        linkToLesson: script_next_path(script, 'next')
      }
    end

    if current_user.teacher?
      unless current_user.donor_teacher_banner_dismissed
        donor_banner_name = current_user.school_donor_name
      end

      donor_banner_name ||= params[:forceDonorTeacherBanner]
      show_census_banner = !!(!donor_banner_name && current_user.show_census_teacher_banner?)

      @homepage_data[:isTeacher] = true
      @homepage_data[:hocLaunch] = DCDO.get('hoc_launch', CDO.default_hoc_launch)
      @homepage_data[:joined_sections] = student_sections
      @homepage_data[:announcement] = DCDO.get('announcement_override', nil)
      @homepage_data[:hiddenScripts] = current_user.get_hidden_script_ids
      @homepage_data[:showCensusBanner] = show_census_banner
      @homepage_data[:donorBannerName] = donor_banner_name

      if show_census_banner
        teachers_school = current_user.school_info.school
        school_stats = SchoolStatsByYear.where(school_id: teachers_school.id).order(school_year: :desc).first

        @homepage_data[:censusQuestion] = school_stats.try(:has_high_school_grades?) ? "how_many_20_hours" : "how_many_10_hours"
        @homepage_data[:currentSchoolYear] = current_census_year
        @homepage_data[:ncesSchoolId] = teachers_school.id
        @homepage_data[:teacherName] = current_user.name
        @homepage_data[:teacherId] = current_user.id
        @homepage_data[:teacherEmail] = current_user.email
      elsif donor_banner_name
        teachers_school = Queries::SchoolInfo.last_complete(current_user)&.school

        donor_teacher_banner_options = {}
        donor_teacher_banner_options[:teacherFirstName] = current_user.short_name
        donor_teacher_banner_options[:teacherSecondName] = current_user.second_name
        donor_teacher_banner_options[:teacherEmail] = current_user.email
        donor_teacher_banner_options[:ncesSchoolId] = teachers_school.id
        donor_teacher_banner_options[:schoolAddress1] = teachers_school.address_line1
        donor_teacher_banner_options[:schoolAddress2] = teachers_school.address_line2
        donor_teacher_banner_options[:schoolAddress3] = teachers_school.address_line3
        donor_teacher_banner_options[:schoolCity] = teachers_school.city
        donor_teacher_banner_options[:schoolState] = teachers_school.state
        donor_teacher_banner_options[:schoolZip] = teachers_school.zip

        @homepage_data[:donorTeacherBannerOptions] = donor_teacher_banner_options

        @homepage_data[:teacherId] = current_user.id
      end
    else
      @homepage_data[:isTeacher] = false
      @homepage_data[:sections] = student_sections
      @homepage_data[:studentId] = current_user.id
    end

    if current_user.school_donor_name
      donor_footer_options = {}
      donor_footer_options[:donorName] = current_user.school_donor_name
      donor_footer_options[:logos] = Dir.glob("app/assets/images/donor_logos/#{current_user.school_donor_name}/*").sort

      @homepage_data[:donorFooterOptions] = donor_footer_options
    end
  end
end

dashboard/app/views/home/_admin.html.haml
- if current_user && current_user.admin?
  = render layout: 'shared/extra_links' do
    %li
      Support tools
      %ul
        %li= link_to 'Assume Identity', assume_identity_form_path
        %li= link_to 'Reset Password', new_user_password_path
        %li= link_to 'Account Repair', account_repair_form_path
        %li= link_to 'Look up section', lookup_section_path
        %li= link_to 'Find Users', find_students_path
    %li= link_to 'Gatekeeper', gatekeeper_show_path
    %li= link_to 'Grant Permissions/Privileges', permissions_form_path
    %li= link_to 'Videos', videos_path
    %li
      = link_to('Scripts', scripts_path)
      = link_to('(Update all)', scripts_path(rake: '1'))
      %ul
        - Script.all.each do |script|
          %li
            = link_to("(#{t 'crud.edit'})", edit_script_path(script))
            = link_to(data_t_suffix('script.name', script.name, 'title'), script_next_path(script))
    %li= link_to t('builder.manage'), new_level_path
    %li= link_to 'Admin Page Directory', admin_directory_path
    %li= link_to 'Gallery', 'projects/public'

dashboard/app/views/home/_all_courses.html.haml
:ruby
  show_state = Gatekeeper.allows('logged_in_studio_homepage', default: true)

  tall_blocks = [
    Script::COURSE1_NAME,
    Script::COURSE2_NAME,
    Script::COURSE3_NAME,
    Script::COURSE4_NAME,
    Script::COURSEA_NAME,
    Script::COURSEB_NAME,
    Script::COURSEC_NAME,
    Script::COURSED_NAME,
    Script::COURSEE_NAME,
    Script::COURSEF_NAME,
    Script::MINECRAFT_AQUATIC_NAME,
    Script::MINECRAFT_HERO_NAME,
    Script::STARWARS_NAME,
    Script::FROZEN_NAME,
    Script::HOC_NAME,
    Script::FLAPPY_NAME,
    Script::INFINITY_NAME,
    Script::PLAYLAB_NAME,
    Script::ARTIST_NAME,
    Script::APPLAB_INTRO,
    Script::DANCE_PARTY_NAME
  ]

  wide_blocks = [
    Script::TWENTY_HOUR_NAME,
    "unplugged",
    Script::EXPRESS_NAME,
    Script::PRE_READER_EXPRESS_NAME,
  ]

.all-course-blocks
  - tall_blocks.each do |script_name|
    %div{id: script_name}
      = render partial: 'shared/course_tall_block', locals: { id: script_name }

  - wide_blocks.each do |script_name|
    %div{id: script_name}
      = render partial: 'shared/course_wide_block', locals: { id: script_name, view: "small" }

.csf-courses-header
  .row
    .span12.twolineheader!= t('home.heading_elementary_markdown', markdown: true)

dashboard/app/views/home/_donor_footer.html.haml
#donor-footer{ style: "background: url(#{asset_path('donor-footer-background.png')}); background-size: cover" }
  %h1
    Code.org thanks our donors
  %p
    Our vision is that every student in every school should have the opportunity to learn computer science. The impact of our work is amplified and made possible with help from our amazing partners.
  %h3
    - if current_user.teacher?
      Your classroom's free use of Code.org is made possible by:
    - else
      Your free education on Code.org is made possible by:
  - @homepage_data[:donorFooterOptions][:logos].each do |logo|
    .logo
      = image_tag asset_path("donor_logos/#{current_user.school_donor_name}/#{logo.split('/').last}")
  - if current_user.teacher? && @homepage_data[:donorFooterOptions][:donorName] == "Amazon"
    %div
      %p.resources
        Amazon is offering free resources for Code.org classrooms.
        %a.learn-more{ href: CDO.code_org_url('amazon-future-engineer') }
          %strong
            Learn more

dashboard/app/views/home/_gallery.html.haml
-show_heading = local_assigns[:show_heading]

.course_progress
  -if show_heading
    .row#lesson
      .span12#heading
        %h3.whitetext{style: 'margin: 0'}
          = t("home.your_gallery")
  .row#stats
    .span12{style: 'margin-left: 10px;'}
      %div.gallery#gallery
        = render partial: 'home/gallery_content'

:javascript
  $(document).ready(function() {
    // Set up gallery pagination.
    $('#gallery').on('click', '.pagination a', function() {
      $.ajax({
        url: $(this).attr('href'),
        data: { },
        success: function(result) {
          $('#gallery').animate(
            {opacity: '25%'},
            500,
            function() {
              $('#gallery').html(result);
            }
          );
        }
      });
      return false;
    });
  });

dashboard/app/views/home/_gallery_content.html.haml
%span.pagination
  = link_to_previous_page @gallery_activities, '', class: 'fa fa-chevron-left', params: {controller: 'home', action: 'gallery_activities'} do '&nbsp;'.html_safe end

- @gallery_activities.each do |gallery_activity|
  - level_source = gallery_activity.try(:level_source)
  - if level_source && level_source.level_source_image
    %div.gallery_activity
      = link_to image_tag(level_source.level_source_image.s3_url), level_source
%span.pagination
  = link_to_next_page @gallery_activities, '', class: 'fa fa-chevron-right', params: {controller: 'home', action: 'gallery_activities'} do '&nbsp;'.html_safe end

dashboard/app/views/home/_gallery_preview.haml
.row
  .span12.twolineheader
    %h2= t('gallery.header')
.row
  .span6.twolineheader
    %h1= t('gallery.header_playlab')
  .span6.twolineheader
    %h1= t('gallery.header_artist')
.row
  .span6
    = link_to image_tag('gallery_thumbnails_2019a.png', width: 460, height: 74), gallery_activities_path
  .span6
    = link_to image_tag('gallery_thumbnails_2019b.png', width: 460, height: 74), gallery_activities_path(anchor: "artist")

dashboard/app/views/home/_levelbuilder.html.haml
- if current_user && current_user.permission?(UserPermission::LEVELBUILDER)
  = render layout: 'shared/extra_links' do
    %li= link_to 'Videos', videos_path
    %li
      = link_to 'Scripts', scripts_path
      = link_to '(Update all)', scripts_path(rake: '1'), data: { confirm: 'Are you sure want to re-seed script data?'}
    %li= link_to t('builder.manage'), levels_path
    %li= link_to 'Pools', pools_path
    %li= link_to 'Shared Functions', shared_blockly_functions_path
    %li= link_to 'Helper Libraries', libraries_path
    %li= link_to 'Gallery', 'projects/public'

dashboard/app/views/home/_projects.html.haml
.course_progress
  %h3.whitetext{style: 'margin: 0'}
    = t("project.projects")
  = link_to projects_path do
    %button.btn.btn-primary.button-continue#continue_button{style: 'margin: 0'}= t('project.view_all')

dashboard/app/views/home/_survey_diversity.haml
- survey_url = "https://docs.google.com/forms/d/e/1FAIpQLScg0PJasQW-uJ3TVR9dIgseGs_xnOHOWLeWJq7bYfIkgjIunA/viewform?usp=pp_url&entry.1305684097=#{current_user.id}"

#diversity_survey
  #surveythanks{style: "display: none; "}
    Thank you for telling us about your students!
    %br/
    %br/
    We're continuing to make improvements to our student and teacher tools.  We'd love your feedback on how we can make them work best for your classroom.
    %br/
    %br/
    %a{href: survey_url, target: "_blank"}
      %button.btn-primary
        Go to survey

  #surveybody
    #headingarea
      %h1 Optional: Help us track our progress toward improving diversity in computer science
      .subtext
        To protect your students’ privacy, we will not ask students younger than 13 for this information. Therefore, this information will not be linked to their specific accounts.
        (See our
        = succeed '.)' do
          %a#privacylink{href: CDO.code_org_url('/privacy'), target: "_blank"} privacy policy

    = form_for(SurveyResult.new, html: {id: 'survey', onsubmit: "return window.submitSurvey(true)"}) do |f|
      .survey_left
        %ol
          %li
            Of your students using Code.org's courses, how many are
        .dots
          - SurveyResult::ETHNICITIES.each do |key, value|
            %input#ethnicity_input{maxlength: "3", name: "survey[diversity_#{key}]", placeholder: "0"}
            = value
            %br/
      .survey_right

        %ol{start: 2}
          %li
            What is the percentage of students with free and reduced meals (FARMs) at your school?
            .subtext
              Only answer this if you're using Code Studio during school hours.
        .dots
          - (0..9).each do |index|
            - if index.between?(0,7)
              - value = index * 10
              - max_value = value == 70 ? 100 : (value+9)
              - text = "#{value}-#{max_value}%"
            - elsif index == 8
              - text = "My school has a Title I designation, but I’m not sure what our rate of Free and Reduced lunch is."
            - else
              - text = "Other"
            .dot
              %input{id: "radio_#{index}", type: "radio", name: "survey[diversity_farm]", value: index}
              %label{for: "radio_#{index}"}= text

      %input{type: "hidden", name: "survey[kind]", value: SurveyResult::DIVERSITY_2019}

      #submit
        %button.btn-primary#submitSurvey{type: "submit"} Submit
        %span#noanswer{onclick: "return submitSurvey(false)"} Prefer not to answer
%br/

:javascript

  function submitSurvey(submittedValue)
  {
    // make sure each ethnicity is a positive integer
    $("#ethnicity_input").each(function(index) {
      $(this).val($(this).val().replace(/[^0-9]/g, ''));
    });

    if (submittedValue)
    {
      $("#surveybody").hide();
      $("#surveythanks").fadeIn();
    }
    else
    {
      $("#survey")[0].reset();
      $("#diversity_survey").hide();
    }

    $.ajax({
      type: 'POST',
      url: $("#survey").attr('action'),
      data: $("#survey").serialize(),
      dataType: 'json'
    });

    // scroll to top of page so that user sees "thank you" even if they had scrolled down
    // to fill out survey.

    $('html,body').animate({scrollTop:0}, 100);

    return false;
  }

dashboard/app/views/home/_tos_and_privacy.html.haml
- @page_title = 'Terms of Service, Privacy Policy, and Privacy Notice'

%h1 Terms of Service
= render partial: 'home/tos'

%hr

%h1 Privacy Policy
= render partial: 'home/privacy'

dashboard/app/views/home/certificate_link_test.haml
- if current_user && current_user.admin?
  - Script.all.each do |script|
    %p= script.name
    %img{width: 350, src: "#{script_certificate_image_url(current_user, script)}"}